### PR TITLE
Use a FlowBox to hold frames in the main window

### PR DESCRIPTION
**Pull request by a33k**
this makes the application much more usable on small screens like that of a phone

### CODE REVIEW

**Comment by marin-m** [comment]
Hello,

Thank you for your pull request. It seems that with this change the window vertically overflows my screen once a song has been recognized, which is likely not the desired result (all the four GtkFrames are then displayed in sequence up-to-bottom, and I precise that I obtain this result when the window is not maximized).

Maybe than an other setup of FlowBox should be used in order to obtain non-overflowing behavior? I began testing other setups on my side.

Regards,

**Comment by a33k** [comment]
I agree this leaves something to be desired. In particular, it seems like the original design would be better matched by a flowbox with GTK_ORIENTATION_VERTICAL, but in that orientation it becomes impossible to shrink the width of the window to a reasonable (or mobile-friendly) size. I think this is due to a rather critical [bug in GTK itself around flowboxes](https://gitlab.gnome.org/GNOME/gtk/-/issues/897), so maybe this should be rethought.

The most well-tested approach to this sort of thing might use [LibHandy](https://source.puri.sm/Librem5/libhandy/-/tree/master) ([docs](https://honk.sigxcpu.org/projects/libhandy/doc/)).

**Comment by a33k** [comment]
I think I've managed to make this approach work much better. The cover art now scales with window resizes, and the flowbox is better behaved. I pushed my changes to this branch--let me know what you think.

**Comment by marin-m** [comment]
Hello,

Thank you for your new changes.

I have pushed a commit so that the margin remain looking mostly the same as before the changes when using the app in a standard desktop setup, and the window has the same default sizes on desktop when opening the app or recognizing a song.

Here are a few remarks regarding the behavior of the application:
* It seems that, when trying to resize to a different size, especially on desktop size setups, the album cover image is frequently displayed as only a truncated part of the original image (a top-left section of the cover) rather that the full image. This seems like a bug to me?
* It seems that when clicking on one of the two halves of the screen, there is an odd focus background that adds to the concerned half (see screenshot). Maybe that this can be avoided by overriding a Gtk signal handler or changing the application's styles.



Regards

**Comment by a33k** [comment]
The focus background comes from the `GtkFlowBox::selection-mode` property; it looks like you already found and fixed that one--sorry!

The image cropping was caused by a line I accidentally dropped from my patch; I'll push a new commit with it in a second.

Thanks for the review!

**Comment by marin-m** [comment]
Hello,

Thanks for your change. The cover seems to scale well. Now there still seems to be an issue with a 1-2 pixels wide black line that often appear at the right, bottom and/or left edge of the image (most often a 1 pixel wide line at the right edge). Do you experience it? Do know whether this may be a rounding bug in Cargo or somewhere?

image

Regards

**Comment by a33k** [comment]
I can't reproduce that issue locally, even carefully watching while resizing the window.

Here's what I see:
no-black-line

Googling I found [this](https://github.com/gtk-rs/gtk/issues/626)--do you think it might be the same issue? What distro, window manager, and cairo/pixman/GTK versions are you using? I'm using Arch Linux/openbox+picom/cairo 1.17.4/pixman 0.40.0/gtk3 3.24.24

**Comment by marin-m** [comment]
Hello,

>Googling I found [this](https://github.com/gtk-rs/gtk/issues/626)--do you think it might be the same issue?

"It puts a narrow black border around the Pixbuf" seems to be an accurate description of the issue.

Please note that it heavily depends of the current size of the window: try to resize it around to various sizes to see it happen (it happens at soon as the size changes). In certain setups it happens, it certain it doesn't.

>What distro, window manager/compositor, and cairo/pixman/GTK versions are you using? I'm using Arch Linux/openbox+picom/cairo 1.17.4/pixman 0.40.0/gtk3 3.24.24

I'm using a standard Ubuntu 20.04, with Libgtk 3.24.20 / Libcairo 1.16.0 / Libpixman 0.38.4.

**Comment by a33k** [comment]
I resized the window a bunch and never saw anything like it. I'll try to reproduce with different setups and keep looking for a root cause.

**Comment by a33k** [comment]
More debugging questions: are you using Wayland, and if not, does this still happen in Wayland? The easiest way to test the latter if your system uses X11 is to install weston, run `weston`, and then run `GDK_BACKEND=wayland songrec`.

**Comment by a33k** [comment]
I just built this branch on an Ubuntu 20.04 VM and still couldn't reproduce the behavior there. I wonder if it could be a bug in accelerated 2D rendering related to X11 drivers.

**Comment by marin-m** [comment]
Hello,

It doesn't reproduce within `weston`. Doesn't reproduce neither with `GDK_RENDERING=image`. Still reproduces obviously with the native X11 rendering.

I'm currently using a Thinkpad T460s with a Intel HD Graphics 520 iGPU. For reference:

```
$ LC_ALL=en_US.UTF8 lshw -c video
  *-display                 
       description: VGA compatible controller
       product: Skylake GT2 [HD Graphics 520]
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 07
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:133 memory:e0000000-e0ffffff memory:c0000000-dfffffff ioport:e000(size=64) memory:c0000-dffff

$ sudo modinfo i915 | grep -Pi 'filename:|depends:|version:'
filename:       /lib/modules/5.8.0-41-generic/kernel/drivers/gpu/drm/i915/i915.ko
srcversion:     B451DDC11D346F62CF3844B
depends:        drm_kms_helper,drm,cec,video,i2c-algo-bit

$ dpkg -S /lib/modules/5.8.0-41-generic/kernel/drivers/gpu/drm/i915/i915.ko
linux-modules-extra-5.8.0-41-generic: /lib/modules/5.8.0-41-generic/kernel/drivers/gpu/drm/i915/i915.ko
```

**Comment by marin-m** [comment]
For the X11 drivers specifically:

```console-session
$ apt search intel | grep inst | grep intel
intel-media-va-driver/focal,now 20.1.1+dfsg1-1 amd64  [installé, automatique]
intel-microcode/focal-updates,focal-security,now 3.20201110.0ubuntu0.20.04.2 amd64  [installé, automatique]
libdrm-intel1/focal-updates,now 2.4.102-1ubuntu1~20.04.1 amd64  [installé, automatique]
xserver-xorg-video-intel/focal,now 2:2.99.917+git20200226-1 amd64  [installé, automatique]
```

I wonder if there is a way to locally disable using acceleration for this surface at the GDK/Cairo level.

**Comment by a33k** [comment]
I made another commit which I think is technically slightly more correct (in that it specifies the exact window we intend to draw onto) and which also forces the pixbuf to have alpha, which may make the black pixels transparent. Any chance it improves things?

The next alternative is to set the `GtkImage` from a pixbuf directly, and do the scaling ourselves with an explicit `gdk_pixbuf_scale_simple` call.

**Comment by marin-m** [comment]
Re,

No change with the 05e0490 commit.

I think that using another drawing/resizing method is a good way to go, if it is a clean way to solve the issue.

**Comment by a33k** [comment]
I pushed a commit that scales the pixbuf manually. Any improvement?

**Comment by marin-m** [comment]
Looks neat enough. The cover image is correctly resized. Thank you! :+1:

**Comment by marin-m** [comment]
@a33k One more question regarding the pull request: it seems that the inner contents of the window can't be edited anymore with the stable Glade (3.38.2) since the FlowBox introductory change.

The children elements are not visible in the tree at the left, and only part of the visible elements (those which are present in the left pane of SongRec) are editable using the "Right click > Edit separately" operation:

image

I have skipped this issue during the review as I felt back on editing the XML `.glade` file directly, but should have done the remark as it makes it harder to edit the interface.

Do you know whether the issue is known? Do you have encountered too? Is there a workaround? May this be related with the Glade version?

Regards,

**Pull request merged**
