### PR TITLE
Right Click Favourites List

### PR DESCRIPTION
**Pull request by damonhayhurst**
- Added additional window that displays favorites
- New context menu option that adds/removes from favorites based on which window the song is selected from
- New favorites csv file

### CODE REVIEW

**Comment by marin-m** [comment]
Hello! 

Thanks for your pull request. 

* It seems that will your pull request, on desktop, the SongRec window now displays on one single column instead of two. Is this wanted? (Maybe that this is due to removing the `min_content_width` and `max_content_width` properties on the GtkApplicationWindow object in the Glade definition file?)
* In the main window, doing a right-click on an item of the favorites lists does not toggle the corresponding context menu item from "Add" to "Remove from favorites". While both "Add" and "Remove" options seem to be present when right-clicking an item in the favorites window (and the "Add to favorites" button seems to be a no-op in the case). Is this wanted behavior?

Regards,

**Comment by damonhayhurst** [comment]
Hi Marin!

- This was not wanted. I've readded  the minimum content dimensions in a new commit.
- I believe so. I feel the song history interface needs to be reimplemented as a hash map for the optimal behaviour. Right clicking would search the list of favorites every time - which could get costly at large list lengths. What do you think? Could get round to doing it in a few months time. A bit bogged down with essays at the moment.

Also what do you think about the new trait pattern for the builder? Effective rust or not?

All the best.

**Comment by damonhayhurst** [comment]
Hi Marin,Any updates on this?On 18 Mar 2023, at 17:48, Marin ***@***.***> wrote:﻿
Hello!
Thanks for your pull request.

It seems that will your pull request, on desktop, the SongRec window now displays on one single column instead of two. Is this wanted? (Maybe that this is due to removing the min_content_width and max_content_width properties on the GtkApplicationWindow object in the Glade definition file?)
In the main window, doing a right-click on an item of the favorites lists does not toggle the corresponding context menu item from "Add" to "Remove from favorites". While both "Add" and "Remove" options seem to be present when right-clicking an item in the favorites window (and the "Add to favorites" button seems to be a no-op in the case). Is this wanted behavior?

Regards,

**Comment by marin-m** [comment]
Hello,

>>It seems that will your pull request, on desktop, the SongRec window now displays on one single column instead of two.
>
>This was not wanted. I've readded the minimum content dimensions in a new commit.

Actually it seems that your last commit doesn't put back the concerned properties in the right object. The properties are but in the GtkFrame object instead of the nested GtkScrolledWindow object, which makes the application crash at startup:

```
(songrec:590283): Gtk-ERROR **: 07:28:11.360: failed to add UI: .:563:61 Invalid property: GtkFrame.min_content_width
```

However, putting back the corresponding properties in the right section still doesn't fix the issue of the window not displaying over two columns in the new setup. It still displays on a single column with I launch it:

image

(I also have the French localization which may make certain button labels larger)

While it's two columns in the stable build:

image

The code in your branch haves the application put back over two columns when the window is resized horizontally.

image

=> The single-column layout is caused by the width of the "Favorites" buttons and the fact that the new three-button horizontal box is not wrapped over many lines when not enough space is available.

I think that it may be fixed through changing the layout type, allowing horizontal items in the button box to overflow over the vertical axis and taking the minimum required space possible.

>> In the main window, doing a right-click on an item of the favorites lists does not toggle the corresponding context menu item from "Add" to "Remove from favorites". While both "Add" and "Remove" options seem to be present when right-clicking an item in the favorites window (and the "Add to favorites" button seems to be a no-op in the case). Is this wanted behavior?
>
> I believe so. I feel the song history interface needs to be reimplemented as a hash map for the optimal behaviour. Right clicking would search the list of favorites every time - which could get costly at large list lengths. What do you think?

* I think that it may be ambiguous and that it is not ergonomic to continue displaying "Add to Favorites" in the corresponding list which the item has already been added to the favorites. The user has no reason to add the concerned item many times to the favorites, and it may be confused thinking that the operation has not worked if the matching option is still displayed in the main music matches lists.
* It may effectively be useful to use an hash map or numeric-indexed array structure to store the state related to each menu item including its presence in the favorite items list, rather that doing a full-list loop of string compare operations on each right click on the main items list.
* I don't think that the "Add to Favorites" option has any reason to be present in the favorites list itself.

Regards,

**Comment by marin-m** [comment]
Hello,

>>It seems that will your pull request, on desktop, the SongRec window now displays on one single column instead of two.
>
>This was not wanted. I've readded the minimum content dimensions in a new commit.

Actually it seems that your last commit doesn't put back the concerned properties in the right object. The properties are but in the GtkFrame object instead of the nested GtkScrolledWindow object, which makes the application crash at startup:

```
(songrec:590283): Gtk-ERROR **: 07:28:11.360: failed to add UI: .:563:61 Invalid property: GtkFrame.min_content_width
```

However, putting back the corresponding properties in the right section still doesn't fix the issue of the window not displaying over two columns in the new setup. It still displays on a single column with I launch it:

image

(I also have the French localization which may make certain button labels larger)

While it's two columns in the stable build:

image

The code in your branch haves the application put back over two columns when the window is resized horizontally.

image

=> The single-column layout is caused by the width of the "Favorites" buttons and the fact that the new three-button horizontal box is not wrapped over many lines when not enough space is available.

I think that it may be fixed through changing the layout type, allowing horizontal items in the button box to overflow over the vertical axis and taking the minimum required space possible.

>> In the main window, doing a right-click on an item of the favorites lists does not toggle the corresponding context menu item from "Add" to "Remove from favorites". While both "Add" and "Remove" options seem to be present when right-clicking an item in the favorites window (and the "Add to favorites" button seems to be a no-op in the case). Is this wanted behavior?
>
> I believe so. I feel the song history interface needs to be reimplemented as a hash map for the optimal behaviour. Right clicking would search the list of favorites every time - which could get costly at large list lengths. What do you think?

* I think that it may be ambiguous and that it is not ergonomic to continue displaying "Add to Favorites" in the corresponding list which the item has already been added to the favorites. The user has no reason to add the concerned item many times to the favorites, and it may be confused thinking that the operation has not worked if the matching option is still displayed in the main music matches lists.
* It may effectively be useful to use an hash map or numeric-indexed array structure to store the state related to each menu item including its presence in the favorite items list, rather that doing a full-list loop of string compare operations on each right click on the main items list.
* I don't think that the "Add to Favorites" option has any reason to be present in the favorites list itself.

Regards,

**Comment by damonhayhurst** [comment]
Hi Marin,

I am unable to recreate the desktop issue on my side. Is it something you might have capacity to fix? I can work on the hash map implementation.

Damon

**Comment by marin-m** [comment]
Hello,

> I am unable to recreate the desktop issue on my side. Do you know a way in which I can recreate the desktop scenario?

As said above I think that this in my case this is due to the width of buttons with the French layout; you might want to edit manually the contents of the corresponding buttons within the Rust code in order to extend this width (I guess that this would be easier that changing the localization on your system).

If this is not sufficient you might want to share more info about your configuration.

> it something you might have capacity to fix?

I have some trouble focusing on code these times (I have a heavy form of ADHD and the symptoms are evolving poor, and I already need to cope with it for day job) but might take a look at it if not otherwise possible

Regards,

**Comment by damonhayhurst** [comment]
I've updated this

- Fixed the window bug
- Glade file is now in-memory store for records
- Songs are evaluated for whether they should be added/removed from favourites on mouse click

**Comment by damonhayhurst** [comment]
Hi Marin, hope you are well. Any updates on this?

**Comment by marin-m** [comment]
Hello,

Seems to work well enough. Merged, thanks!

**Pull request merged**
