### PR TITLE
Added track key to csv output

### PR DESCRIPTION
**Pull request by tyd**
I've been using the continuous CSV output for a while and it's been working great! However, I wanted to be able to get more info about tracks by using the key and calling the Shazam site. So I added a new field to capture the 'key' field value from the original JSON response and I added it to the CSV output as the last field called 'track_key'

**New CSV Output Example:**
song_name,album,recognition_date,track_key
Flowdan Feat. Irah - Level,Level (feat. Irah) - EP,Thu Oct 14 22:50:12 2021,**464064459**

Then you can use the track key value at the end to call the following URL and get the JSON:
https://www.shazam.com/discovery/v5/en-US/US/web/-/track/464064459?shazamapiversion=v3

And also easily get the number of Shazams:
https://www.shazam.com/services/count/v2/web/track/464064459

**Note:** If you have an existing song_history.csv file, you may need to delete it before it will output the new structure.

### CODE REVIEW

**Comment by marin-m** [comment]
Hello,

Thank you for your pull request. As you can see through running your branch on a device that already had a formed version of SongRec installed (outside Flatpak), having the application trying to run while a CSV file formatted in the former recognition log file format (without the file that you added being present) causes the application to crash at the launch, with the following error message:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Deserialize { pos: Some(Position { byte: 33, line: 2, record: 1 }), err: DeserializeError { field: None, kind: Message("missing field `track_key`") } })', src/gui/main_window.rs:103:119
```

That's because the version of `rust-csv` that I use is quite rigid and doesn't accept having missing/extra fields when deserializing from a structure, IIRC.

I think that it would be good that recognition history files formatted in the former recognition file format would be correctly migrated towards the newer recognition file format. It may require to change the parsing method used for the concerned CSV file and/or adding extra heuristic code outside it. I think that having the application crashing at the launch without extra user action when a former version of the application was used is not acceptable.

Regards,

**Comment by tyd** [comment]
@marin-m I'll see what I can do to fix it

**Comment by tyd** [comment]
@marin-m was able to change over to `csv::ReaderBuilder` and add the `.flexible(true)` option to get it working with older files.

**Comment by marin-m** [comment]
Hello,

Thank your for your change.

I have also added "Release year" and "Genre" columns within the CSV song recognition history, as this seems to have been suggested in issues #36 and #70.

I have not added the concerned fields to the GUI yet, as I'm not sure whether it would be good to make the contents of the song recognition frame history larger, as it already may be large although scrollable with certain track names.

Would you have an opinion about this?

Regards,

**Comment by tyd** [comment]
I think the real estate in the UI recognition history is pretty much maxed out. 

Perhaps an alternative (and separate task) would be to allow the user to click on songs in the history list and have that populate a new area with detailed track information displayed? It could default to latest track, or click on any other track in the history and populate the info

**Comment by marin-m** [comment]
Thank you for your feedback. I am merging the changes for now!

**Pull request merged**
