### PR TITLE
Add arch build packages 

### PR DESCRIPTION
**Pull request by kepet19**
I made a new folder called 'distro' and then arch to later add other distro's

### CODE REVIEW

**Comment by marin-m** [comment]
Hello,

Thanks for your PR.

I have split the package into `songrec` and `songrec-git` package, and made a few improvement such as adding build dependencies. Does it look right to you?

If so, I think that I will merge and upload it to AUR.

Regards,

**Comment by kepet19** [comment]
Hey 
I add provides and 'conflicts' to the 'package' build.
So now it know both of the packages are conflict with each other. 
I tested both version and they seem to work well. 

When the Archlinux version tries to build it failed, so I temporary add this variable 
_pkgname=SongRec. 
When it have downloaded the release from github and extracted it. It then tries to change dir, it fails because the folder  name is 'SongRec' instead of the lowercase version 'songrec'.

**Comment by kepet19** [comment]
It seems good to me now! 
Just tested the change.
 works as expected.

**Comment by marin-m** [comment]
Thank you,

I have pushed the new packages to AUR:
* https://aur.archlinux.org/packages/songrec/
* https://aur.archlinux.org/packages/songrec-git/

Regarding the other distributions, the Flathub package is still pending approval and I have started studying the possibility of a Snap package.

I'm merging this pull request.

**Comment by kepet19** [comment]
image

Thanks for helping with the PR 
And thans for mering it! 

Here is a celebrate pic!

**Pull request merged**
