### PR TITLE
Expose current song metadata via MPRIS

### PR DESCRIPTION
**Pull request by Hummer12007**
This PR adds a daemon subcommand which exposes the currently recognized song via the MPRIS DBus interface.

### CODE REVIEW

**Comment by marin-m** [comment]
Hello,

Thank you for your PR.

When trying to test the module with another SongRec (GUI or not) instance opened aside on my Ubuntu install, no usable input sound device is detected by the ALSA library binding and hence, your module crashes abruptly with an error:

```console-session
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/mpris/mpris_main.rs:85:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I'm not sure whether this can be avoided, but maybe that at least a more human-readable message could be printed to the user?

Also, in order to keep the code base organized, maybe that you could put a small `README.md` file at the root of the `src/mpris/` directory that you added that describes in greater detail the purpose and moreover the functioning (what is MPRIS in a few words, where does the module take input audio and what exactly does it send to MPRIS, etc.) of the code that you added?

Regards,

**Comment by Hummer12007** [comment]
Did a little rework: integrated MPRIS support with GUI code.

**Comment by Hummer12007** [comment]
With regards to code structure:

Maybe we should do it the following way?:
```
src
├── cli
│   └── cli_main.rs
├── core
│   ├── csv_song_history.rs
│   ├── http_thread.rs
│   ├── microphone_thread.rs
│   ├── processing_thread.rs
│   └── thread_messages.rs
├── fingerprinting
│   ├── algorithm.rs
│   ├── communication.rs
│   ├── hanning.rs
│   ├── signature_format.rs
│   └── user_agent.rs
├── gui
│   ├── gui_main.rs
│   └── interface.glade
├── main.rs
└── utils
    ├── ffmpeg_wrapper.rs
    ├── internationalization.rs
    ├── mpris_player.rs
    └── pulseaudio_loopback.rs
```

**Comment by marin-m** [comment]
Hello,

This looks like a good idea.

**Comment by Hummer12007** [comment]
>When trying to test the module with another SongRec (GUI or not) instance opened aside on my Ubuntu install, no usable input sound device is detected by the ALSA library binding and hence, your module crashes abruptly with an error:

Hm, I can launch an arbitrary number of SongRec instances (both mpris-daemon and gui) with no issues (I have a pure ALSA system though). Will take a look at a Pulse-based system.

**Comment by marin-m** [comment]
This was observed while using Ubuntu 20.04 LTS with PulseAudio.

Launching a stable SongRec GUI in a Flatpak environment aside a stable SongRec GUI in a non-Flatpak environment seems to suffice to reproduce though (the regular SongRec GUI is meant to be single-instance due to the DBus singleton application centralization routine).

This is weird as in the past, I didn't remember that SongRec was instance-limited in any way. Maybe that is related with recent kernel or `alsalib`/PulseAudio versions.

**Comment by Hummer12007** [comment]
Done. Is there anything else you'd like to address?

**Comment by marin-m** [comment]
It looks pretty well organized. Thank you for your neat work!

* I think that it would be good to add a `--list-devices` or similar flag so that the input device can be chosen or selected in a fully command-line environment.

* I think that the `recognize` command should be renamed into something like `microphone-to-recognized-song`, and that the input file recognition feature could be left as `audio-file-to-recognized-song` as it is the case currently.

* Maybe that the `mpris-daemon` subcommand could be merged into `cli` in order to simplify the command-line interface, as the functionality seems to be duplicated here.

I'll remember to maybe add some more documentation to the CLI (that I may extend) and to internationalize the new help strings to French later.

Note that the JSON output provided by the current prototype is really a serialized internal state rather than the full JSON information returned by the Shazam servers (see the behavior of the current `audio-to-recognized-song` command). Maybe it's sufficient to most users (it doesn't include some extra information like the various track, artist and album cover art URLs).

**Comment by Hummer12007** [comment]
I'll make the CLI simpler a bit later. Does the last commit look good?

**Comment by marin-m** [comment]
The idea of making GUI libraries optional looks ok to me. Maybe that the GUI should be made opt-out rather than opt-in in order to avoid to break the build processes for various distributions package or make the `cargo install`-based commands shared at various places stale though.

The pattern with macros looks ok. It seems to me that Clap.rs has alternatives to this particular builder pattern that could avoid this but it's readable enough.

**Comment by Hummer12007** [comment]
The GUI should be opt-out (i.e. it's the default feature).

**Comment by Hummer12007** [comment]
With regards to CLI: I don't really agree with your suggestion about microphone-to..., the commands should be easy to type IMO.
I'll try coming up with something less confusing than the current version though.

**Comment by marin-m** [comment]
I'd just like the command naming to be internally consistent, and preferably the backwards compatibility of the command line interface to be kept. I think that adding shorthand aliases could be a good tradeoff, if straightforward and Clap.rs allows it.

**Comment by Hummer12007** [comment]
The new CLI approach:

* Add a `microphone-to-recognized-song` command
* Add a`recognize` command which would recognize a song from either a file or a mic depending on the args.
* Add a `listen` command which would continuously listen and recognize the song and expose the info with MPRIS (optionally).

**Comment by marin-m** [comment]
Hello,

It looks pretty nice.

I tested and the core functionality works.

I notice that the `--audio-device` argument is not functional though:
* Trying to execute `cargo run --release -- listen --audio-device surround40` displays that the current code excepts a non-string taking argument: `error: Found argument 'surround40' which wasn't expected, or isn't valid in this context`
* Trying to execute `cargo run --release -- recognize --audio-device ANYTHING` displays that it is not taken in account at all

I guess that the `.alias("foo")` line in `src/main.rs` was left unintentionally.

Once fixed, please tell me if you want to make extra changes or if I can edit/merge. I think that I will turn the 5 positional arguments of `cli::cli_main::cli_main` into a `CLIParameters` structure for better readability.

**Comment by Hummer12007** [comment]
Thanks for noticing (probably deleted takes_value by mistake at some point)!
This should be ready.

**Comment by marin-m** [comment]
Merged, thanks!

**Comment by Hummer12007** [comment]
Yay, thanks!

**Pull request merged**
